language: python
python:
  - "3.5"
  - "3.6"
install:
  - GRAPHITE_NO_PREFIX=1 pip install pytest-cov lmdb==0.94 msgpack==0.5.1 graphite-web==1.1.3 xxhash
  - python setup.py build_ext --inplace
script: py.test
